#!/usr/bin/env bash
# displays bad luck on 8 then best school

NUM=1
while [ $NUM -lt 11 ]
do
    if [ $NUM = 4 ]
    then
        echo "bad luck"
    elif [ $NUM = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( NUM+=1 ))
done
